//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentSlider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentSlider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 of 3.
        /// </summary>
        public static string Step1_Line1 {
            get {
                return ResourceManager.GetString("Step1_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1_Line2 Step1_Line2 Step1_Line2.
        /// </summary>
        public static string Step1_Line2 {
            get {
                return ResourceManager.GetString("Step1_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1_Line3 Step1_Line3 Step1_Line3.
        /// </summary>
        public static string Step1_Line3 {
            get {
                return ResourceManager.GetString("Step1_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2 of 3.
        /// </summary>
        public static string Step2_Line1 {
            get {
                return ResourceManager.GetString("Step2_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2_Line2 Step2_Line2 Step2_Line2 Step2_Line2 Step2_Line2.
        /// </summary>
        public static string Step2_Line2 {
            get {
                return ResourceManager.GetString("Step2_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2_Line3 Step2_Line3 Step2_Line3.
        /// </summary>
        public static string Step2_Line3 {
            get {
                return ResourceManager.GetString("Step2_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3 of 3.
        /// </summary>
        public static string Step3_Line1 {
            get {
                return ResourceManager.GetString("Step3_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3_Line2 Step3_Line2 Step3_Line2 Step3_Line2 Step3_Line2.
        /// </summary>
        public static string Step3_Line2 {
            get {
                return ResourceManager.GetString("Step3_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3_Line3 Step3_Line3 Step3_Line3.
        /// </summary>
        public static string Step3_Line3 {
            get {
                return ResourceManager.GetString("Step3_Line3", resourceCulture);
            }
        }
    }
}
